CREATE TABLE CURSO(
    ID_CURSO INTEGER PRIMARY KEY, NOME_CURSO VARCHAR(50),
    NOME_TURNO_CURSO VARCHAR(50)
);

INSERT INTO CURSO VALUES(1, 'PEDAGOGIA', 'CURSO A DISTÂNCIA');
INSERT INTO CURSO VALUES